"""stable attachment composite via partId

Revision ID: 1c965f28e09a
Revises: 515b1b73d67d
Create Date: 2026-04-27 08:23:59.371059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c965f28e09a'
down_revision: Union[str, Sequence[str], None] = '515b1b73d67d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('part_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('gmail_attachment_id', sa.Text(), nullable=True))

    # Existing attachment rows used the volatile ``gmail_attachment_id`` as
    # part of the composite primary key. Those IDs expire after a few hours,
    # so any pre-existing rows are either stale (their ``id`` no longer
    # corresponds to a downloadable attachment) or duplicated across syncs.
    # Wipe them and reset messages back to ``pending`` so the next sync
    # rebuilds the table correctly using the stable ``part_id`` composite.
    op.execute("DELETE FROM detections")
    op.execute("DELETE FROM message_verdicts")
    op.execute("DELETE FROM attachments")
    op.execute(
        "UPDATE messages SET sync_status='pending', synced_at=NULL, "
        "attachment_count=NULL, has_attachments=NULL"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_column('gmail_attachment_id')
        batch_op.drop_column('part_id')

    # ### end Alembic commands ###
