"""initial schema

Revision ID: 515b1b73d67d
Revises: 
Create Date: 2026-04-27 07:20:47.047858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '515b1b73d67d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('total_attachments', sa.Integer(), nullable=True),
    sa.Column('processed_attachments', sa.Integer(), nullable=True),
    sa.Column('config_snapshot', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('syncs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('total_messages', sa.Integer(), nullable=True),
    sa.Column('synced_messages', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=True),
    sa.Column('sync_id', sa.Integer(), nullable=True),
    sa.Column('sender', sa.Text(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('has_attachments', sa.Boolean(), nullable=True),
    sa.Column('attachment_count', sa.Integer(), nullable=True),
    sa.Column('sync_status', sa.String(length=32), nullable=False),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sync_id'], ['syncs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('idx_messages_sync_status', ['sync_status'], unique=False)

    op.create_table('attachments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('blob_path', sa.Text(), nullable=True),
    sa.Column('sync_status', sa.String(length=32), nullable=False),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(), nullable=True),
    sa.Column('last_scan_id', sa.Integer(), nullable=True),
    sa.Column('extraction_route', sa.String(length=32), nullable=True),
    sa.Column('extraction_status', sa.String(length=32), nullable=True),
    sa.Column('extracted_text_path', sa.Text(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(), nullable=True),
    sa.Column('extraction_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['last_scan_id'], ['scans.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index('idx_attachments_extraction', ['extraction_status'], unique=False)
        batch_op.create_index('idx_attachments_hash', ['content_hash'], unique=False)
        batch_op.create_index('idx_attachments_message', ['message_id'], unique=False)

    op.create_table('message_verdicts',
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('top_category', sa.String(length=32), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('category_summary', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    with op.batch_alter_table('message_verdicts', schema=None) as batch_op:
        batch_op.create_index('idx_verdicts_flagged', ['is_flagged', 'risk_score'], unique=False)

    op.create_table('detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('attachment_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('subtype', sa.String(length=64), nullable=True),
    sa.Column('detector', sa.String(length=32), nullable=False),
    sa.Column('span_text', sa.Text(), nullable=True),
    sa.Column('span_start', sa.Integer(), nullable=True),
    sa.Column('span_end', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachments.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detections', schema=None) as batch_op:
        batch_op.create_index('idx_detections_attachment', ['attachment_id'], unique=False)
        batch_op.create_index('idx_detections_scan', ['scan_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detections', schema=None) as batch_op:
        batch_op.drop_index('idx_detections_scan')
        batch_op.drop_index('idx_detections_attachment')

    op.drop_table('detections')
    with op.batch_alter_table('message_verdicts', schema=None) as batch_op:
        batch_op.drop_index('idx_verdicts_flagged')

    op.drop_table('message_verdicts')
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index('idx_attachments_message')
        batch_op.drop_index('idx_attachments_hash')
        batch_op.drop_index('idx_attachments_extraction')

    op.drop_table('attachments')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('idx_messages_sync_status')

    op.drop_table('messages')
    op.drop_table('syncs')
    op.drop_table('scans')
    # ### end Alembic commands ###
