"""add mailbox_scope to syncs

Revision ID: a0f801a1c96c
Revises: 1c965f28e09a
Create Date: 2026-05-17 12:23:01.373141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0f801a1c96c'
down_revision: Union[str, Sequence[str], None] = '1c965f28e09a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('syncs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mailbox_scope', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('syncs', schema=None) as batch_op:
        batch_op.drop_column('mailbox_scope')

    # ### end Alembic commands ###
